[QI2-1126] Added compiler_configs to static reply
QuTech-Delft/compute-runtime-schema pull request #11
Opened 2024-10-29 09:24 UTC by NischalQuTech

2024-10-29 09:31 UTC, oschusler requested changes

2024-10-29 09:31 UTC, oschusler commented on docs/request/index.md
> +            "mapped": [
should be updated to a name that reflects the content. This will raise questions. Chris mentioned a number of stages yesterday, I think one of the was decomposition or something?

2024-10-29 09:31 UTC, oschusler commented on docs/request/index.md
> +                    "pass": "opensquirrel.decomposers.MckayDecomposer",
can you check whether the module path and method are correct?

2024-10-29 09:55 UTC, oschusler approved these changes
Do keep the MR open until you've heard from the HWCS teams

2024-10-29 10:06 UTC, NischalQuTech commented on docs/request/index.md
> +                    "pass": "opensquirrel.decomposers.MckayDecomposer",
Corrected path. Method is correct

2024-10-29 10:07 UTC, NischalQuTech commented on docs/request/index.md
> +            "mapped": [
I have changed it to decomposition for now. Also asked Chris. will update it

2024-10-29 12:48 UTC, Mythir commented on docs/request/index.md
> +        "compiler_config": {
@oschusler @NischalQuTech maybe `default_compiler_config` would be more suitable? That aligns better with Chris' view, as he wants (knowledgeable) users to be able to configure compilation themselves.

2024-10-29 12:51 UTC, oschusler commented on docs/request/index.md
> +        "compiler_config": {
This configuration is for the "catch all" compilers at the end (the one in the API and the one in the QDC). If you want to specify the compilation yourself, this happens in the SDK. The ones in the API and QDC will always compile against a default configuration

2024-10-29 13:35 UTC, Mythir commented on docs/request/index.md
> +        "compiler_config": {
As just discussed on Slack, we are in agreement that the user should not change the configuration steps that happen in the QDC, but the user should be able to skip some (or all) of them. My argument for `default_compiler_config` still stands, but I have no strong feelings about this, it was only a naming suggestion.

2024-10-29 13:37 UTC, oschusler commented on docs/request/index.md
> +        "compiler_config": {
@NischalQuTech lets change it to `default_compiler_config`

2024-10-29 13:57 UTC, Mythir requested changes

2024-10-29 13:57 UTC, Mythir commented on docs/request/index.md
> +                    "pass": "opensquirrel.decomposer.mckay_decomposer.McKayDecomposer",
I just realised having a Python keyword as a field name is not very practical 😅 . Maybe go for `compiler_pass`?

2024-10-29 13:57 UTC, Mythir commented on docs/request/index.md
> +                    "pass": "opensquirrel.decomposer.mckay_decomposer.McKayDecomposer",
@oschusler @NischalQuTech

2024-10-29 14:00 UTC, oschusler commented on docs/request/index.md
> +                    "pass": "opensquirrel.decomposer.mckay_decomposer.McKayDecomposer",
Valid point. In the original proposal it was called `compiler_pass`, but it feels a bit redundant. The thing is about compiler_config, which already suggests that the `pass` is for the compiler. That said, maybe it's not even an actual pass but something that you pass along to the method (in this case a decomposer). For the latter, is there a more generic term which we might be able to use?

2024-10-29 14:06 UTC, Mythir commented on docs/request/index.md
> +                    "pass": "opensquirrel.decomposer.mckay_decomposer.McKayDecomposer",
I suggest we follow the naming of `method` and `kwargs` and go for something that exposes the OpenSquirrel implementation. (Which is entirely defensible because tightly coupling this to the implementation is our goal). In which case you could go for `path`.

2024-10-29 14:25 UTC, oschusler commented on docs/request/index.md
> +                    "pass": "opensquirrel.decomposer.mckay_decomposer.McKayDecomposer",
@Mythir you don't wanna fight mypy??

2024-10-29 14:27 UTC, NischalQuTech commented on docs/request/index.md
> +            "mapped": [
confirmed with Chris, what we do currently is indeed `decomposition` stage

2024-10-29 14:36 UTC, Mythir commented on docs/request/index.md
> +                    "pass": "opensquirrel.decomposer.mckay_decomposer.McKayDecomposer",
The few times I tried MyPy came off without a scratch, and I was left bleeding on the floor

2024-10-30 09:40 UTC, Mythir approved these changes

2024-10-30 12:12 UTC, eliasKA approved these changes

2024-10-30 12:12 UTC, merged

2024-10-31 15:27 UTC, klkl0808 commented
Does this PR also change the version string in the message? Or do we stick to `0.1.0`?