[QI2-1279] Publish documentation to GitHub pages
QuTech-Delft/compute-runtime-schema pull request #19
Opened 2024-12-31 13:36 UTC by oschusler

2025-01-02 15:34 UTC, Mythir requested changes

2025-01-02 15:34 UTC, Mythir commented on .github/workflows/docs.yaml
> +            mike set-default --push latest
Does the default ever change? (If no, why are setting this every time?)

2025-01-02 15:34 UTC, Mythir commented on .github/workflows/docs.yaml
> +          mike set-default --push latest
Deploy as <ref_name> and then set "latest" as default?

2025-01-03 07:39 UTC, oschusler commented on .github/workflows/docs.yaml
> +            mike set-default --push latest
It never changes. The operation itself however is idempotent. We set it however, since the pipeline is the only one who (can) have an opinion on it and if anything would ever happen to th `gh-pages` branch, this would always restore it to the appropriate value.

2025-01-03 07:40 UTC, oschusler commented on .github/workflows/docs.yaml
> +          mike set-default --push latest
That's correct. All of our documentation (also platform for example), points to latest as default version. For production deployments, there are also versions though.

2025-01-03 09:29 UTC, Mythir approved these changes

2025-01-03 10:28 UTC, merged